// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tnwt.play.entity;

import com.tnwt.play.entity.PlayerDataOnDemand;
import com.tnwt.play.entity.PlayerIntegrationTest;
import com.tnwt.play.repository.PlayerRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PlayerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlayerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlayerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private PlayerDataOnDemand PlayerIntegrationTest.dod;
    
    @Autowired
    PlayerRepository PlayerIntegrationTest.playerRepository;
    
    @Test
    public void PlayerIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", dod.getRandomPlayer());
        long count = playerRepository.count();
        Assert.assertTrue("Counter for 'Player' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlayerIntegrationTest.testFind() {
        Player obj = dod.getRandomPlayer();
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Player' failed to provide an identifier", id);
        obj = playerRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Player' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Player' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlayerIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", dod.getRandomPlayer());
        long count = playerRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Player', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Player> result = playerRepository.findAll();
        Assert.assertNotNull("Find all method for 'Player' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Player' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlayerIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", dod.getRandomPlayer());
        long count = playerRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Player> result = playerRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Player' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Player' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlayerIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", dod.getRandomPlayer());
        Player obj = dod.getNewTransientPlayer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Player' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Player' identifier to be null", obj.getId());
        playerRepository.save(obj);
        Assert.assertNotNull("Expected 'Player' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlayerIntegrationTest.testDelete() {
        Player obj = dod.getRandomPlayer();
        Assert.assertNotNull("Data on demand for 'Player' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Player' failed to provide an identifier", id);
        obj = playerRepository.findOne(id);
        playerRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Player' with identifier '" + id + "'", playerRepository.findOne(id));
    }
    
}
